import Footer from './components/Footer'
import Header from './components/Header'
// import M2cteam from './components/M2cteam'
// import Contact from './contact/page'
// import CreateProfile from './createProfile/page'
// import Services from './services/page'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        {/* <CreateProfile /> */}
        {/* <Services /> */}
        {/* <Contact /> */}
        {/* <M2cteam /> */}
        <Footer />
      </body>
    </html>
  )
}
